ALTER TABLE "Loan" ADD COLUMN "paidOff" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Loan" ADD COLUMN "mortgageInsurance" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Loan" ADD COLUMN "otherFees" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "LoanSnapshot" ADD COLUMN "paymentAmount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "LoanSnapshot" ADD COLUMN "principalAmount" INTEGER NOT NULL DEFAULT 0;
